name: machinelearning
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pandas
  - lime
  - datasets
  - scikit-learn
  - umap-learn
  - imbalanced-learn
  - scipy
  - seaborn
  - xgboost
  - transformers[torch]
  - optuna
  - numpy
  - matplotlib
  - statsmodels
  - ipykernel
  - pylint
  - pytest
  - isort
  - pip
  - pip:
    - ucimlrepo
    - kagglehub
    - torch